# ~/.config/nvim/rc/dein.toml

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'cocopon/lightline-hybrid.vim'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'def-lkb/ocp-indent-vim'

[[plugins]]
repo = 'jvoorhis/coq.vim'

[[plugins]]
repo = 'vim-perl/vim-perl'
