# ~/.config/nvim/rc/dein.toml

# basis

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'cocopon/lightline-hybrid.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

# colorscheme

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'reedes/vim-colors-pencil'

# specific language supports

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'reasonml-editor/vim-reason-plus'

[[plugins]]
repo = 'jvoorhis/coq.vim'

[[plugins]]
repo = 'vim-perl/vim-perl'
